#! /bin/bash

echo ram
cat     n1 | grep ram
cat     n2 | grep ram
cat     n3 | grep ram
cat     n4 | grep ram
cat     n5 | grep ram
cat     n6 | grep ram
cat     n7 | grep ram
cat     n8 | grep ram
cat     n9 | grep ram
cat     n10 | grep ram
cat     n11 | grep ram
cat     n12 | grep ram
cat     n13 | grep ram
cat     n14 | grep ram
cat     n15 | grep ram
cat     n16 | grep ram
cat     n17 | grep ram
cat     n18 | grep ram
cat     n19 | grep ram
cat     n20 | grep ram
cat     n21 | grep ram
cat     n22 | grep ram
cat     n23 | grep ram
cat     n24 | grep ram
cat     n25 | grep ram
cat     n26 | grep ram
cat     n27 | grep ram
cat     n28 | grep ram
cat     n29 | grep ram
cat     n30 | grep ram
cat     n31 | grep ram
cat     n32 | grep ram
cat     n33 | grep ram
cat     n34 | grep ram
cat     n35 | grep ram
cat     n36 | grep ram
cat     n37 | grep ram
cat     n38 | grep ram
cat     n39 | grep ram
cat     n40 | grep ram
cat     n41 | grep ram
cat     n42 | grep ram
cat     n43 | grep ram
cat     n44 | grep ram
cat     n45 | grep ram
cat     n46 | grep ram
cat     n47 | grep ram
cat     n48 | grep ram
cat     n49 | grep ram
cat     n50 | grep ram
cat     n51 | grep ram
cat     n52 | grep ram
cat     n53 | grep ram
cat     n54 | grep ram
cat     n55 | grep ram
cat     n56 | grep ram
cat     n57 | grep ram
cat     n58 | grep ram
cat     n59 | grep ram
cat     n60 | grep ram
cat     n61 | grep ram
cat     n62 | grep ram
cat     n63 | grep ram
cat     n64 | grep ram
cat     n65 | grep ram
cat     n66 | grep ram
cat     n67 | grep ram
cat     n68 | grep ram
cat     n69 | grep ram
cat     n70 | grep ram
cat     n71 | grep ram
cat     n72 | grep ram
cat     n73 | grep ram
cat     n74 | grep ram
cat     n75 | grep ram
cat     n76 | grep ram
cat     n77 | grep ram
cat     n78 | grep ram
cat     n79 | grep ram
cat     n80 | grep ram
cat     n81 | grep ram
cat     n82 | grep ram
cat     n83 | grep ram
cat     n84 | grep ram
cat     n85 | grep ram
cat     n86 | grep ram
cat     n87 | grep ram
cat     n88 | grep ram
cat     n89 | grep ram
cat     n90 | grep ram
cat     n91 | grep ram
cat     n92 | grep ram
cat     n93 | grep ram
cat     n94 | grep ram
cat     n95 | grep ram
cat     n96 | grep ram
echo second
cat     n1 | grep second
cat     n2 | grep second
cat     n3 | grep second
cat     n4 | grep second
cat     n5 | grep second
cat     n6 | grep second
cat     n7 | grep second
cat     n8 | grep second
cat     n9 | grep second
cat     n10 | grep second
cat     n11 | grep second
cat     n12 | grep second
cat     n13 | grep second
cat     n14 | grep second
cat     n15 | grep second
cat     n16 | grep second
cat     n17 | grep second
cat     n18 | grep second
cat     n19 | grep second
cat     n20 | grep second
cat     n21 | grep second
cat     n22 | grep second
cat     n23 | grep second
cat     n24 | grep second
cat     n25 | grep second
cat     n26 | grep second
cat     n27 | grep second
cat     n28 | grep second
cat     n29 | grep second
cat     n30 | grep second
cat     n31 | grep second
cat     n32 | grep second
cat     n33 | grep second
cat     n34 | grep second
cat     n35 | grep second
cat     n36 | grep second
cat     n37 | grep second
cat     n38 | grep second
cat     n39 | grep second
cat     n40 | grep second
cat     n41 | grep second
cat     n42 | grep second
cat     n43 | grep second
cat     n44 | grep second
cat     n45 | grep second
cat     n46 | grep second
cat     n47 | grep second
cat     n48 | grep second
cat     n49 | grep second
cat     n50 | grep second
cat     n51 | grep second
cat     n52 | grep second
cat     n53 | grep second
cat     n54 | grep second
cat     n55 | grep second
cat     n56 | grep second
cat     n57 | grep second
cat     n58 | grep second
cat     n59 | grep second
cat     n60 | grep second
cat     n61 | grep second
cat     n62 | grep second
cat     n63 | grep second
cat     n64 | grep second
cat     n65 | grep second
cat     n66 | grep second
cat     n67 | grep second
cat     n68 | grep second
cat     n69 | grep second
cat     n70 | grep second
cat     n71 | grep second
cat     n72 | grep second
cat     n73 | grep second
cat     n74 | grep second
cat     n75 | grep second
cat     n76 | grep second
cat     n77 | grep second
cat     n78 | grep second
cat     n79 | grep second
cat     n80 | grep second
cat     n81 | grep second
cat     n82 | grep second
cat     n83 | grep second
cat     n84 | grep second
cat     n85 | grep second
cat     n86 | grep second
cat     n87 | grep second
cat     n88 | grep second
cat     n89 | grep second
cat     n90 | grep second
cat     n91 | grep second
cat     n92 | grep second
cat     n93 | grep second
cat     n94 | grep second
cat     n95 | grep second
cat     n96 | grep second

echo pkg
cat     n1 | grep pkg
cat     n2 | grep pkg
cat     n3 | grep pkg
cat     n4 | grep pkg
cat     n5 | grep pkg
cat     n6 | grep pkg
cat     n7 | grep pkg
cat     n8 | grep pkg
cat     n9 | grep pkg
cat     n10 | grep pkg
cat     n11 | grep pkg
cat     n12 | grep pkg
cat     n13 | grep pkg
cat     n14 | grep pkg
cat     n15 | grep pkg
cat     n16 | grep pkg
cat     n17 | grep pkg
cat     n18 | grep pkg
cat     n19 | grep pkg
cat     n20 | grep pkg
cat     n21 | grep pkg
cat     n22 | grep pkg
cat     n23 | grep pkg
cat     n24 | grep pkg
cat     n25 | grep pkg
cat     n26 | grep pkg
cat     n27 | grep pkg
cat     n28 | grep pkg
cat     n29 | grep pkg
cat     n30 | grep pkg
cat     n31 | grep pkg
cat     n32 | grep pkg
cat     n33 | grep pkg
cat     n34 | grep pkg
cat     n35 | grep pkg
cat     n36 | grep pkg
cat     n37 | grep pkg
cat     n38 | grep pkg
cat     n39 | grep pkg
cat     n40 | grep pkg
cat     n41 | grep pkg
cat     n42 | grep pkg
cat     n43 | grep pkg
cat     n44 | grep pkg
cat     n45 | grep pkg
cat     n46 | grep pkg
cat     n47 | grep pkg
cat     n48 | grep pkg
cat     n49 | grep pkg
cat     n50 | grep pkg
cat     n51 | grep pkg
cat     n52 | grep pkg
cat     n53 | grep pkg
cat     n54 | grep pkg
cat     n55 | grep pkg
cat     n56 | grep pkg
cat     n57 | grep pkg
cat     n58 | grep pkg
cat     n59 | grep pkg
cat     n60 | grep pkg
cat     n61 | grep pkg
cat     n62 | grep pkg
cat     n63 | grep pkg
cat     n64 | grep pkg
cat     n65 | grep pkg
cat     n66 | grep pkg
cat     n67 | grep pkg
cat     n68 | grep pkg
cat     n69 | grep pkg
cat     n70 | grep pkg
cat     n71 | grep pkg
cat     n72 | grep pkg
cat     n73 | grep pkg
cat     n74 | grep pkg
cat     n75 | grep pkg
cat     n76 | grep pkg
cat     n77 | grep pkg
cat     n78 | grep pkg
cat     n79 | grep pkg
cat     n80 | grep pkg
cat     n81 | grep pkg
cat     n82 | grep pkg
cat     n83 | grep pkg
cat     n84 | grep pkg
cat     n85 | grep pkg
cat     n86 | grep pkg
cat     n87 | grep pkg
cat     n88 | grep pkg
cat     n89 | grep pkg
cat     n90 | grep pkg
cat     n91 | grep pkg
cat     n92 | grep pkg
cat     n93 | grep pkg
cat     n94 | grep pkg
cat     n95 | grep pkg
cat     n96 | grep pkg

echo second
cat     a1 | grep second
cat     a2 | grep second
cat     a3 | grep second
cat     a4 | grep second
cat     a5 | grep second
cat     a6 | grep second
cat     a7 | grep second
cat     a8 | grep second
cat     a9 | grep second
cat     a10 | grep second
cat     a11 | grep second
cat     a12 | grep second
cat     a13 | grep second
cat     a14 | grep second
cat     a15 | grep second
cat     a16 | grep second
cat     a17 | grep second
cat     a18 | grep second
cat     a19 | grep second
cat     a20 | grep second
cat     a21 | grep second
cat     a22 | grep second
cat     a23 | grep second
cat     a24 | grep second
cat     a25 | grep second
cat     a26 | grep second
cat     a27 | grep second
cat     a28 | grep second
cat     a29 | grep second
cat     a30 | grep second
cat     a31 | grep second
cat     a32 | grep second
cat     a33 | grep second
cat     a34 | grep second
cat     a35 | grep second
cat     a36 | grep second
cat     a37 | grep second
cat     a38 | grep second
cat     a39 | grep second
cat     a40 | grep second
cat     a41 | grep second
cat     a42 | grep second
cat     a43 | grep second
cat     a44 | grep second
cat     a45 | grep second
cat     a46 | grep second
cat     a47 | grep second
cat     a48 | grep second
echo pkg
cat     a1 | grep pkg
cat     a2 | grep pkg
cat     a3 | grep pkg
cat     a4 | grep pkg
cat     a5 | grep pkg
cat     a6 | grep pkg
cat     a7 | grep pkg
cat     a8 | grep pkg
cat     a9 | grep pkg
cat     a10 | grep pkg
cat     a11 | grep pkg
cat     a12 | grep pkg
cat     a13 | grep pkg
cat     a14 | grep pkg
cat     a15 | grep pkg
cat     a16 | grep pkg
cat     a17 | grep pkg
cat     a18 | grep pkg
cat     a19 | grep pkg
cat     a20 | grep pkg
cat     a21 | grep pkg
cat     a22 | grep pkg
cat     a23 | grep pkg
cat     a24 | grep pkg
cat     a25 | grep pkg
cat     a26 | grep pkg
cat     a27 | grep pkg
cat     a28 | grep pkg
cat     a29 | grep pkg
cat     a30 | grep pkg
cat     a31 | grep pkg
cat     a32 | grep pkg
cat     a33 | grep pkg
cat     a34 | grep pkg
cat     a35 | grep pkg
cat     a36 | grep pkg
cat     a37 | grep pkg
cat     a38 | grep pkg
cat     a39 | grep pkg
cat     a40 | grep pkg
cat     a41 | grep pkg
cat     a42 | grep pkg
cat     a43 | grep pkg
cat     a44 | grep pkg
cat     a45 | grep pkg
cat     a46 | grep pkg
cat     a47 | grep pkg
cat     a48 | grep pkg
echo ram
cat     a1 | grep ram
cat     a2 | grep ram
cat     a3 | grep ram
cat     a4 | grep ram
cat     a5 | grep ram
cat     a6 | grep ram
cat     a7 | grep ram
cat     a8 | grep ram
cat     a9 | grep ram
cat     a10 | grep ram
cat     a11 | grep ram
cat     a12 | grep ram
cat     a13 | grep ram
cat     a14 | grep ram
cat     a15 | grep ram
cat     a16 | grep ram
cat     a17 | grep ram
cat     a18 | grep ram
cat     a19 | grep ram
cat     a20 | grep ram
cat     a21 | grep ram
cat     a22 | grep ram
cat     a23 | grep ram
cat     a24 | grep ram
cat     a25 | grep ram
cat     a26 | grep ram
cat     a27 | grep ram
cat     a28 | grep ram
cat     a29 | grep ram
cat     a30 | grep ram
cat     a31 | grep ram
cat     a32 | grep ram
cat     a33 | grep ram
cat     a34 | grep ram
cat     a35 | grep ram
cat     a36 | grep ram
cat     a37 | grep ram
cat     a38 | grep ram
cat     a39 | grep ram
cat     a40 | grep ram
cat     a41 | grep ram
cat     a42 | grep ram
cat     a43 | grep ram
cat     a44 | grep ram
cat     a45 | grep ram
cat     a46 | grep ram
cat     a47 | grep ram
cat     a48 | grep ram
