cat	a1 | grep second
cat	a2 | grep second
cat	a3 | grep second
cat	a4 | grep second
cat	a5 | grep second
cat	a6 | grep second
cat	a7 | grep second
cat	a8 | grep second
cat	a9 | grep second
cat	a10 | grep second
cat	a11 | grep second
cat	a12 | grep second
cat	a13 | grep second
cat	a14 | grep second
cat	a15 | grep second
cat	a16 | grep second
cat	a17 | grep second
cat	a18 | grep second
cat	a19 | grep second
cat	a20 | grep second
cat	a21 | grep second
cat	a22 | grep second
cat	a23 | grep second
cat	a24 | grep second
cat	a25 | grep second
cat	a26 | grep second
cat	a27 | grep second
cat	a28 | grep second
cat	a29 | grep second
cat	a30 | grep second
cat	a31 | grep second
cat	a32 | grep second
cat	a33 | grep second
cat	a34 | grep second
cat	a35 | grep second
cat	a36 | grep second
cat	a37 | grep second
cat	a38 | grep second
cat	a39 | grep second
cat	a40 | grep second
cat	a41 | grep second
cat	a42 | grep second
cat	a43 | grep second
cat	a44 | grep second
cat	a45 | grep second
cat	a46 | grep second
cat	a47 | grep second
cat	a48 | grep second

cat	a1 | grep pkg
cat	a2 | grep pkg
cat	a3 | grep pkg
cat	a4 | grep pkg
cat	a5 | grep pkg
cat	a6 | grep pkg
cat	a7 | grep pkg
cat	a8 | grep pkg
cat	a9 | grep pkg
cat	a10 | grep pkg
cat	a11 | grep pkg
cat	a12 | grep pkg
cat	a13 | grep pkg
cat	a14 | grep pkg
cat	a15 | grep pkg
cat	a16 | grep pkg
cat	a17 | grep pkg
cat	a18 | grep pkg
cat	a19 | grep pkg
cat	a20 | grep pkg
cat	a21 | grep pkg
cat	a22 | grep pkg
cat	a23 | grep pkg
cat	a24 | grep pkg
cat	a25 | grep pkg
cat	a26 | grep pkg
cat	a27 | grep pkg
cat	a28 | grep pkg
cat	a29 | grep pkg
cat	a30 | grep pkg
cat	a31 | grep pkg
cat	a32 | grep pkg
cat	a33 | grep pkg
cat	a34 | grep pkg
cat	a35 | grep pkg
cat	a36 | grep pkg
cat	a37 | grep pkg
cat	a38 | grep pkg
cat	a39 | grep pkg
cat	a40 | grep pkg
cat	a41 | grep pkg
cat	a42 | grep pkg
cat	a43 | grep pkg
cat	a44 | grep pkg
cat	a45 | grep pkg
cat	a46 | grep pkg
cat	a47 | grep pkg
cat	a48 | grep pkg

cat	a1 | grep ram
cat	a2 | grep ram
cat	a3 | grep ram
cat	a4 | grep ram
cat	a5 | grep ram
cat	a6 | grep ram
cat	a7 | grep ram
cat	a8 | grep ram
cat	a9 | grep ram
cat	a10 | grep ram
cat	a11 | grep ram
cat	a12 | grep ram
cat	a13 | grep ram
cat	a14 | grep ram
cat	a15 | grep ram
cat	a16 | grep ram
cat	a17 | grep ram
cat	a18 | grep ram
cat	a19 | grep ram
cat	a20 | grep ram
cat	a21 | grep ram
cat	a22 | grep ram
cat	a23 | grep ram
cat	a24 | grep ram
cat	a25 | grep ram
cat	a26 | grep ram
cat	a27 | grep ram
cat	a28 | grep ram
cat	a29 | grep ram
cat	a30 | grep ram
cat	a31 | grep ram
cat	a32 | grep ram
cat	a33 | grep ram
cat	a34 | grep ram
cat	a35 | grep ram
cat	a36 | grep ram
cat	a37 | grep ram
cat	a38 | grep ram
cat	a39 | grep ram
cat	a40 | grep ram
cat	a41 | grep ram
cat	a42 | grep ram
cat	a43 | grep ram
cat	a44 | grep ram
cat	a45 | grep ram
cat	a46 | grep ram
cat	a47 | grep ram
cat	a48 | grep ram

