#! /bin/bash

  
echo ram
cat     jj1 | grep ram
cat     jj2 | grep ram
cat     jj3 | grep ram
cat     jj4 | grep ram
cat     jj5 | grep ram
cat     jj6 | grep ram
cat     jj7 | grep ram
cat     jj8 | grep ram
cat     jj9 | grep ram
cat     jj10 | grep ram
cat     jj11 | grep ram
cat     jj12 | grep ram
cat     jj13 | grep ram
cat     jj14 | grep ram
cat     jj15 | grep ram
cat     jj16 | grep ram
cat     jj17 | grep ram
cat     jj18 | grep ram
cat     jj19 | grep ram
cat     jj20 | grep ram
cat     jj21 | grep ram
cat     jj22 | grep ram
cat     jj23 | grep ram
cat     jj24 | grep ram
cat     jj25 | grep ram
cat     jj26 | grep ram
cat     jj27 | grep ram
cat     jj28 | grep ram
cat     jj29 | grep ram
cat     jj30 | grep ram
cat     jj31 | grep ram
cat     jj32 | grep ram
cat     jj33 | grep ram
cat     jj34 | grep ram
cat     jj35 | grep ram
cat     jj36 | grep ram
cat     jj37 | grep ram
cat     jj38 | grep ram
cat     jj39 | grep ram
cat     jj40 | grep ram
cat     jj41 | grep ram
cat     jj42 | grep ram
cat     jj43 | grep ram
cat     jj44 | grep ram
cat     jj45 | grep ram
cat     jj46 | grep ram
cat     jj47 | grep ram
cat     jj48 | grep ram
cat     jj49 | grep ram
cat     jj50 | grep ram
cat     jj51 | grep ram
cat     jj52 | grep ram
cat     jj53 | grep ram
cat     jj54 | grep ram
cat     jj55 | grep ram
cat     jj56 | grep ram
cat     jj57 | grep ram
cat     jj58 | grep ram
cat     jj59 | grep ram
cat     jj60 | grep ram
cat     jj61 | grep ram
cat     jj62 | grep ram
cat     jj63 | grep ram
cat     jj64 | grep ram
cat     jj65 | grep ram
cat     jj66 | grep ram
cat     jj67 | grep ram
cat     jj68 | grep ram
cat     jj69 | grep ram
cat     jj70 | grep ram
cat     jj71 | grep ram
cat     jj72 | grep ram
cat     jj73 | grep ram
cat     jj74 | grep ram
cat     jj75 | grep ram
cat     jj76 | grep ram
cat     jj77 | grep ram
cat     jj78 | grep ram
cat     jj79 | grep ram
cat     jj80 | grep ram
cat     jj81 | grep ram
cat     jj82 | grep ram
cat     jj83 | grep ram
cat     jj84 | grep ram
cat     jj85 | grep ram
cat     jj86 | grep ram
cat     jj87 | grep ram
cat     jj88 | grep ram
cat     jj89 | grep ram
cat     jj90 | grep ram
cat     jj91 | grep ram
cat     jj92 | grep ram
cat     jj93 | grep ram
cat     jj94 | grep ram
cat     jj95 | grep ram
cat     jj96 | grep ram
echo second
cat     jj1 | grep second
cat     jj2 | grep second
cat     jj3 | grep second
cat     jj4 | grep second
cat     jj5 | grep second
cat     jj6 | grep second
cat     jj7 | grep second
cat     jj8 | grep second
cat     jj9 | grep second
cat     jj10 | grep second
cat     jj11 | grep second
cat     jj12 | grep second
cat     jj13 | grep second
cat     jj14 | grep second
cat     jj15 | grep second
cat     jj16 | grep second
cat     jj17 | grep second
cat     jj18 | grep second
cat     jj19 | grep second
cat     jj20 | grep second
cat     jj21 | grep second
cat     jj22 | grep second
cat     jj23 | grep second
cat     jj24 | grep second
cat     jj25 | grep second
cat     jj26 | grep second
cat     jj27 | grep second
cat     jj28 | grep second
cat     jj29 | grep second
cat     jj30 | grep second
cat     jj31 | grep second
cat     jj32 | grep second
cat     jj33 | grep second
cat     jj34 | grep second
cat     jj35 | grep second
cat     jj36 | grep second
cat     jj37 | grep second
cat     jj38 | grep second
cat     jj39 | grep second
cat     jj40 | grep second
cat     jj41 | grep second
cat     jj42 | grep second
cat     jj43 | grep second
cat     jj44 | grep second
cat     jj45 | grep second
cat     jj46 | grep second
cat     jj47 | grep second
cat     jj48 | grep second
cat     jj49 | grep second
cat     jj50 | grep second
cat     jj51 | grep second
cat     jj52 | grep second
cat     jj53 | grep second
cat     jj54 | grep second
cat     jj55 | grep second
cat     jj56 | grep second
cat     jj57 | grep second
cat     jj58 | grep second
cat     jj59 | grep second
cat     jj60 | grep second
cat     jj61 | grep second
cat     jj62 | grep second
cat     jj63 | grep second
cat     jj64 | grep second
cat     jj65 | grep second
cat     jj66 | grep second
cat     jj67 | grep second
cat     jj68 | grep second
cat     jj69 | grep second
cat     jj70 | grep second
cat     jj71 | grep second
cat     jj72 | grep second
cat     jj73 | grep second
cat     jj74 | grep second
cat     jj75 | grep second
cat     jj76 | grep second
cat     jj77 | grep second
cat     jj78 | grep second
cat     jj79 | grep second
cat     jj80 | grep second
cat     jj81 | grep second
cat     jj82 | grep second
cat     jj83 | grep second
cat     jj84 | grep second
cat     jj85 | grep second
cat     jj86 | grep second
cat     jj87 | grep second
cat     jj88 | grep second
cat     jj89 | grep second
cat     jj90 | grep second
cat     jj91 | grep second
cat     jj92 | grep second
cat     jj93 | grep second
cat     jj94 | grep second
cat     jj95 | grep second
cat     jj96 | grep second


cat     jj1 | grep pkg
cat     jj2 | grep pkg
cat     jj3 | grep pkg
cat     jj4 | grep pkg
cat     jj5 | grep pkg
cat     jj6 | grep pkg
cat     jj7 | grep pkg
cat     jj8 | grep pkg
cat     jj9 | grep pkg
cat     jj10 | grep pkg
cat     jj11 | grep pkg
cat     jj12 | grep pkg
cat     jj13 | grep pkg
cat     jj14 | grep pkg
cat     jj15 | grep pkg
cat     jj16 | grep pkg
cat     jj17 | grep pkg
cat     jj18 | grep pkg
cat     jj19 | grep pkg
cat     jj20 | grep pkg
cat     jj21 | grep pkg
cat     jj22 | grep pkg
cat     jj23 | grep pkg
cat     jj24 | grep pkg
cat     jj25 | grep pkg
cat     jj26 | grep pkg
cat     jj27 | grep pkg
cat     jj28 | grep pkg
cat     jj29 | grep pkg
cat     jj30 | grep pkg
cat     jj31 | grep pkg
cat     jj32 | grep pkg
cat     jj33 | grep pkg
cat     jj34 | grep pkg
cat     jj35 | grep pkg
cat     jj36 | grep pkg
cat     jj37 | grep pkg
cat     jj38 | grep pkg
cat     jj39 | grep pkg
cat     jj40 | grep pkg
cat     jj41 | grep pkg
cat     jj42 | grep pkg
cat     jj43 | grep pkg
cat     jj44 | grep pkg
cat     jj45 | grep pkg
cat     jj46 | grep pkg
cat     jj47 | grep pkg
cat     jj48 | grep pkg
cat     jj49 | grep pkg
cat     jj50 | grep pkg
cat     jj51 | grep pkg
cat     jj52 | grep pkg
cat     jj53 | grep pkg
cat     jj54 | grep pkg
cat     jj55 | grep pkg
cat     jj56 | grep pkg
cat     jj57 | grep pkg
cat     jj58 | grep pkg
cat     jj59 | grep pkg
cat     jj60 | grep pkg
cat     jj61 | grep pkg
cat     jj62 | grep pkg
cat     jj63 | grep pkg
cat     jj64 | grep pkg
cat     jj65 | grep pkg
cat     jj66 | grep pkg
cat     jj67 | grep pkg
cat     jj68 | grep pkg
cat     jj69 | grep pkg
cat     jj70 | grep pkg
cat     jj71 | grep pkg
cat     jj72 | grep pkg
cat     jj73 | grep pkg
cat     jj74 | grep pkg
cat     jj75 | grep pkg
cat     jj76 | grep pkg
cat     jj77 | grep pkg
cat     jj78 | grep pkg
cat     jj79 | grep pkg
cat     jj80 | grep pkg
cat     jj81 | grep pkg
cat     jj82 | grep pkg
cat     jj83 | grep pkg
cat     jj84 | grep pkg
cat     jj85 | grep pkg
cat     jj86 | grep pkg
cat     jj87 | grep pkg
cat     jj88 | grep pkg
cat     jj89 | grep pkg
cat     jj90 | grep pkg
cat     jj91 | grep pkg
cat     jj92 | grep pkg
cat     jj93 | grep pkg
cat     jj94 | grep pkg
cat     jj95 | grep pkg
cat     jj96 | grep pkg


echo jjk
cat    jjk1 | grep second
cat    jjk2 | grep second
cat    jjk3 | grep second
cat    jjk4 | grep second
cat    jjk5 | grep second
cat    jjk6 | grep second
cat    jjk7 | grep second
cat    jjk8 | grep second
cat    jjk9 | grep second
cat    jjk10 | grep second
cat    jjk11 | grep second
cat    jjk12 | grep second
cat    jjk13 | grep second
cat    jjk14 | grep second
cat    jjk15 | grep second
cat    jjk16 | grep second
cat    jjk17 | grep second
cat    jjk18 | grep second
cat    jjk19 | grep second
cat    jjk20 | grep second
cat    jjk21 | grep second
cat    jjk22 | grep second
cat    jjk23 | grep second
cat    jjk24 | grep second
cat    jjk25 | grep second
cat    jjk26 | grep second
cat    jjk27 | grep second
cat    jjk28 | grep second
cat    jjk29 | grep second
cat    jjk30 | grep second
cat    jjk31 | grep second
cat    jjk32 | grep second
cat    jjk33 | grep second
cat    jjk34 | grep second
cat    jjk35 | grep second
cat    jjk36 | grep second
cat    jjk37 | grep second
cat    jjk38 | grep second
cat    jjk39 | grep second
cat    jjk40 | grep second
cat    jjk41 | grep second
cat    jjk42 | grep second
cat    jjk43 | grep second
cat    jjk44 | grep second
cat    jjk45 | grep second
cat    jjk46 | grep second
cat    jjk47 | grep second
cat    jjk48 | grep second
echo pkg
cat    jjk1 | grep pkg
cat    jjk2 | grep pkg
cat    jjk3 | grep pkg
cat    jjk4 | grep pkg
cat    jjk5 | grep pkg
cat    jjk6 | grep pkg
cat    jjk7 | grep pkg
cat    jjk8 | grep pkg
cat    jjk9 | grep pkg
cat    jjk10 | grep pkg
cat    jjk11 | grep pkg
cat    jjk12 | grep pkg
cat    jjk13 | grep pkg
cat    jjk14 | grep pkg
cat    jjk15 | grep pkg
cat    jjk16 | grep pkg
cat    jjk17 | grep pkg
cat    jjk18 | grep pkg
cat    jjk19 | grep pkg
cat    jjk20 | grep pkg
cat    jjk21 | grep pkg
cat    jjk22 | grep pkg
cat    jjk23 | grep pkg
cat    jjk24 | grep pkg
cat    jjk25 | grep pkg
cat    jjk26 | grep pkg
cat    jjk27 | grep pkg
cat    jjk28 | grep pkg
cat    jjk29 | grep pkg
cat    jjk30 | grep pkg
cat    jjk31 | grep pkg
cat    jjk32 | grep pkg
cat    jjk33 | grep pkg
cat    jjk34 | grep pkg
cat    jjk35 | grep pkg
cat    jjk36 | grep pkg
cat    jjk37 | grep pkg
cat    jjk38 | grep pkg
cat    jjk39 | grep pkg
cat    jjk40 | grep pkg
cat    jjk41 | grep pkg
cat    jjk42 | grep pkg
cat    jjk43 | grep pkg
cat    jjk44 | grep pkg
cat    jjk45 | grep pkg
cat    jjk46 | grep pkg
cat    jjk47 | grep pkg
cat    jjk48 | grep pkg
echo ram
cat    jjk1 | grep ram
cat    jjk2 | grep ram
cat    jjk3 | grep ram
cat    jjk4 | grep ram
cat    jjk5 | grep ram
cat    jjk6 | grep ram
cat    jjk7 | grep ram
cat    jjk8 | grep ram
cat    jjk9 | grep ram
cat    jjk10 | grep ram
cat    jjk11 | grep ram
cat    jjk12 | grep ram
cat    jjk13 | grep ram
cat    jjk14 | grep ram
cat    jjk15 | grep ram
cat    jjk16 | grep ram
cat    jjk17 | grep ram
cat    jjk18 | grep ram
cat    jjk19 | grep ram
cat    jjk20 | grep ram
cat    jjk21 | grep ram
cat    jjk22 | grep ram
cat    jjk23 | grep ram
cat    jjk24 | grep ram
cat    jjk25 | grep ram
cat    jjk26 | grep ram
cat    jjk27 | grep ram
cat    jjk28 | grep ram
cat    jjk29 | grep ram
cat    jjk30 | grep ram
cat    jjk31 | grep ram
cat    jjk32 | grep ram
cat    jjk33 | grep ram
cat    jjk34 | grep ram
cat    jjk35 | grep ram
cat    jjk36 | grep ram
cat    jjk37 | grep ram
cat    jjk38 | grep ram
cat    jjk39 | grep ram
cat    jjk40 | grep ram
cat    jjk41 | grep ram
cat    jjk42 | grep ram
cat    jjk43 | grep ram
cat    jjk44 | grep ram
cat    jjk45 | grep ram
cat    jjk46 | grep ram
cat    jjk47 | grep ram
cat    jjk48 | grep ram


